### ISSUE TITLE
context clobbers geo: URL scheme

### ISSUE THREAD

**Issue by VladimirAlexiev** [lanthaler/vCardOntology#1]
https://en.wikipedia.org/wiki/Geo_URI_scheme defines the `geo:` absolute URL.
But a URL like `<geo:51.36824,-0.40229>` gets clobbered to `<vcard:geo51.36824,-0.40229>` because the vcard context redefines it like so:
```js
    "geo": { "@id": "vcard:geo", "@type": "@id" },
```

AFAI can see, the same file `combined.jsonld` from this repo is deployed officially to http://www.w3.org/2006/vcard/ns.jsonld

**Comment by lanthaler** [comment]
Right. You can't have it both. What would you suggest?

**Comment by VladimirAlexiev** [comment]
Use names-with-colons for properties and classes, eg
```js
"vcard:geo": {"@type": "@id" },
```
The big discussion is in https://github.com/json-ld/json-ld.org/issues/469

**Comment by lanthaler** [comment]
Why would you use a context then instead of just defining that prefix? For the type coercion? I can surely add a context that does just that but I feel it doesn’t provide that much value.

**Comment by VladimirAlexiev** [comment]
"geo" conflicts between vcard and schema (so you can't use the two together), in addition to clobbering the `geo:` URI scheme.
IMHO contexts shouldn't use names-without-colons for props and classes. See the big discussion.

**Comment by lanthaler** [comment]
Most people prefer it that way, myself included. The colon makes working with data as JSON way harder. You can always choose to create a context that suits your needs better. I'm closing this issue as it is non-actionable. Feel free open another issue or send a pull request if you want to add another context that doesn't define these terms but still provides values for applications like yours.

**Comment by VladimirAlexiev** [comment]
You also clobber the `tel:` scheme. See this thread https://twitter.com/ontotext/status/844156511811223552
